### ISSUE TITLE
Helios Co2 sensor

### ISSUE THREAD

**Issue by ingosb** [frawe/EasyControls3_homeassistant#2]
Many thanks for the great work, the integration works with a KWL 170 without any problems.
Is it possible to read out and integrate the original Helios Co2 sensor that is connected to the KWL 170?

![Co2](https://github.com/user-attachments/assets/edc54189-6b2e-49c3-be7c-ae79c378f803)

**Comment by frawe** [comment]
hi, I think it should be possible, but I have a different variant. So I would need information and wireshark dumps from you to get it in.

**Comment by ingosb** [comment]
What exactly do you need?
A Wireshark dump while I am accessing the easyControls 3.0 start page of the ventilation system, or when I access the ventilation system via lan?

**Comment by frawe** [comment]
Do you have an acc at https://community.home-assistant.io? Then we could write there private.

You should be able to find me there via this https://community.home-assistant.io/t/helios-easycontrol-3-0-to-homeassistant-custom-integration/763749 (I am obviously the creator ;) )

**Comment by frawe** [comment]
Is integrated in releases after the above mentioned commit.
