### ISSUE TITLE
Fan speed for home/away states

### ISSUE THREAD

**Issue by mgrfilipmarek** [frawe/EasyControls3_homeassistant#4]
It would be nice to have possibility to set the fan speed for states "at home" and "away". Would it be doable?

**Comment by frawe** [comment]
should be possible, maybe in one of the next versions.

**Comment by frawe** [comment]
i added it today, would be great if you could test it out and led me know if you see any problems, then I will create a new release with it. You would need to have a commit equal to or later than 5d04cfa45d9e5ae72a796578dd82e9d24d82d9b4.

**Comment by mgrfilipmarek** [comment]
looks fine, can be merged/released.

**Comment by frawe** [comment]
is already commited (se above) and will be in next release
